### ISSUE TITLE
Use of initializer lists in tests without type leads to ambiguity (e.g., Box and Ray)

### ISSUE THREAD

**Issue by wjge** [arborx/ArborX#435]
1. The function `ArborX::Details::intersects(const ArborX::Box &, const ArborX::Box &)` and function `ArborX::Details::intersects(const ArborX::Ray &, const ArborX::Box &)` are reported to have the same argument type: {{...},{...}}.
2. Should the `ArborX::Details::intersects(const ArborX::Ray &, const ArborX::Box &)` be put in the `ArborX_DetailsAlgorithms.hpp`? or should `ArborX_DetailsAlgorithms.hpp #include ArborX_Ray.hpp`?

**Comment by aprokop** [comment]
Essentially, we should not use initializer lists without a type preceding them, if only for clarity.

**Comment by aprokop** [comment]
@dalg24 

> How do we reproduce? You have no other choice than explicitly say whether you mean Box or Ray

You can simply add `#include <ArborX_Ray.hpp>` in `ArborX_DetailsAlgorithm.hpp`.

> I don't see a compelling reason to change anything at the moment

I was hitting the same issue in my work when a new geometry was introduced (a plane).

Overall, I don't see any downside for explicitly writing `Box{{...}}` and `Sphere{{...},.}` instead of `{{...}}`. Personally, I also find it easier to understand what's being done rather than trying to remember the constructors/initializers.

**Comment by dalg24** [comment]
I am specifically addressing the question Wenjun asked.  Feel free to disambiguate where necessary.
