### ISSUE TITLE
Narow-phase collision detection for complex particle shapes on Kokkos

### ISSUE THREAD

**Issue by Shihab-Shahriar** [arborx/ArborX#983]
It's less of an "issue" with ArborX and more of a request for suggestion.

I need to do collision detection for complex shapes (but convex, say spherocylinders or tetrahedron). After I do broad-phase detection using ArborX, is there any library I can use to find actually colliding particles that is compatible with Kokkos?

**Comment by aprokop** [comment]
I'm not aware of a library in the Kokkos ecosystem. I think what you need is an implementation of the [GJK](https://en.wikipedia.org/wiki/Gilbert%E2%80%93Johnson%E2%80%93Keerthi_distance_algorithm) algorithm to call within ArborX callback. The only requirement would be to write the shape functions as `KOKKOS_FUNCTION` so that they can be run within Kokkos kernel.

It would be interesting to see that in ArborX.

**Comment by Shihab-Shahriar** [comment]
Thanks for the suggestion.

**Comment by aprokop** [comment]
I would probably look at https://github.com/MattiaMontanari/openGJK/, as it is based on an [updated GJK paper](https://dl.acm.org/doi/10.1145/3083724) that fixes some of the tolerance issues with the original.
